import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: { index: 'index-src.ts' },
  outDir: '.',
  format: ['cjs'],
  external: [
    'react',
    'react-dom',
    'react-redux',
    'styled-components',
    'redux-observers',
    'redux',
    'reselect',
    'fast-memoize',
    'lodash',
    'classnames',
    'path',
    'bluebird',
    'fs-extra',
    'path-extra',
    'react-fontawesome',
    'react-i18next',
    '@blueprintjs/core',
    'views/components/etc/window-env',
    'views/env-parts/i18next',
    'views/utils/selectors',
    'views/utils/tools',
    'views/components/etc/overlay',
    'views/create-store',
    'views/utils/ship-img',
    'views/components/etc/avatar',
    'views/components/etc/icon',
    'views/utils/game-utils',
  ],
  outExtensions: () => ({ js: '.js' }),
  clean: false,
  sourcemap: true,
  treeshake: true,
  shims: false,
  target: false,
})
