name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Build lib-battle
      working-directory: lib/battle
      run: |
        npm ci
        npm run build

    - name: Install deps
      run: |
        npm ci

    - name: Type check
      run: |
        npm run typecheck

    - name: Lint
      run: |
        npm run lint

    - name: Test with coverage
      run: |
        npm run test:coverage

    - name: Build
      run: |
        npm run build
